# Generated by Django 5.2.5 on 2025-09-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_status', '0001_initial'),
        ('histories_configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories_configurations.history', verbose_name='Historial'),
        ),
    ]
