# Generated by Django 5.2.5 on 2025-09-04 15:26

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_status', '0002_initial'),
        ('histories_configurations', '0003_payment_status_fix'),
        ('patients_diagnoses', '0001_initial'),
        ('reflexo', '__first__'),
    ]

    # Helper to drop existing patient_id safely if it exists
    def _drop_patient_id_if_exists(apps, schema_editor):
        with connection.cursor() as cursor:
            # Check if column exists
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'appointments'
                  AND COLUMN_NAME = 'patient_id'
                """
            )
            (count,) = cursor.fetchone()
            if count == 0:
                return

            # Drop FK constraint if present
            cursor.execute(
                """
                SELECT CONSTRAINT_NAME
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = 'appointments'
                  AND COLUMN_NAME = 'patient_id'
                  AND REFERENCED_TABLE_NAME IS NOT NULL
                """
            )
            rows = cursor.fetchall()
            for (constraint_name,) in rows:
                cursor.execute(f"ALTER TABLE appointments DROP FOREIGN KEY `{constraint_name}`;")

            # Finally drop the column
            cursor.execute("ALTER TABLE appointments DROP COLUMN `patient_id`;")

    operations = [
        migrations.RunPython(_drop_patient_id_if_exists, migrations.RunPython.noop),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.paymentstatus', verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.paymenttype', verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
    ]
