# Generated by Django 5.2.5 on 2025-09-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_status', '0003_initial'),
        ('reflexo', '__first__'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='therapists.therapist', verbose_name='Terapeuta'),
        ),
        migrations.AddField(
            model_name='appointmentstatus',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_status.appointment', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'hour'], name='appointment_appoint_7d154e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_status'], name='appointment_appoint_80fbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatus',
            index=models.Index(fields=['name'], name='appointment_name_b2e8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_ticket__4c9624_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment_date'], name='tickets_payment_5ac8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_fbbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['appointment'], name='tickets_appoint_0b3be5_idx'),
        ),
    ]
