# Generated by Django 5.2.5 on 2025-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0004_initial'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del estado'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstatus',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_appt_status_per_reflexo_name'),
        ),
    ]
