# Generated by Django 5.2.5 on 2025-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0005_alter_appointmentstatus_name_and_more'),
        ('histories_configurations', '0006_remove_documenttype_uniq_document_type_per_reflexo_name_and_more'),
        ('patients_diagnoses', '0003_alter_medicalrecord_unique_together'),
        ('reflexo', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la cita'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=50, verbose_name='Número de ticket'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient', 'history'), name='uniq_active_patient_history'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('appointment',), name='uniq_active_ticket_per_appointment'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('reflexo', 'ticket_number'), name='uniq_ticket_number_per_reflexo'),
        ),
    ]
