# Generated by Django 5.2.5 on 2025-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0006_alter_appointment_appointment_status_and_more'),
        ('histories_configurations', '0007_alter_history_options_history_local_id_and_more'),
        ('patients_diagnoses', '0004_alter_patient_options_patient_local_id_and_more'),
        ('reflexo', '0001_initial'),
        ('therapists', '0002_alter_therapist_options_therapist_local_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['reflexo_id', 'local_id', '-appointment_date', '-hour'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='local_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID local (por empresa)'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('reflexo', 'local_id'), name='uniq_appointment_local_id_per_reflexo'),
        ),
    ]
