# Generated by Django 5.2.5 on 2025-09-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0007_alter_appointment_options_appointment_local_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_appoint_b25c11_idx',
            old_name='appointment_appoint_80fbf2_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments_status.appointmentstatus', verbose_name='Estado de la cita'),
        ),
    ]
