# Generated by Django 5.2.5 on 2025-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0008_rename_appointment_appoint_80fbf2_idx_appointment_appoint_b25c11_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentstatus',
            name='uniq_appt_status_per_reflexo_name',
        ),
        migrations.RemoveField(
            model_name='appointmentstatus',
            name='reflexo',
        ),
        migrations.AddConstraint(
            model_name='appointmentstatus',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_appt_status_name'),
        ),
    ]
