# Generated by Django 5.2.5 on 2025-09-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('histories_configurations', '0001_initial'),
        ('patients_diagnoses', '0001_initial'),
        ('reflexo', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='history',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
    ]
