# Generated by Cascade to ensure payment_status table exists before FKs reference it
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
                CREATE TABLE IF NOT EXISTS `payment_status` (
                  `id` int NOT NULL AUTO_INCREMENT,
                  `name` varchar(100) NOT NULL,
                  `description` varchar(255) NULL,
                  PRIMARY KEY (`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
                """
            ),
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
