# Generated by Django 5.2.5 on 2025-09-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0003_payment_status_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'managed': True, 'verbose_name': 'Estado de pago', 'verbose_name_plural': 'Estados de pago'},
        ),
    ]
