# Generated by Django 5.2.5 on 2025-09-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0004_alter_paymentstatus_options'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddField(
            model_name='predeterminedprice',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_document_type_per_reflexo_name'),
        ),
        migrations.AddConstraint(
            model_name='paymentstatus',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_payment_status_per_reflexo_name'),
        ),
        migrations.AddConstraint(
            model_name='paymenttype',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_payment_type_per_reflexo_name'),
        ),
        migrations.AddConstraint(
            model_name='predeterminedprice',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_predetermined_price_per_reflexo_name'),
        ),
    ]
