# Generated by Django 5.2.5 on 2025-09-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0005_documenttype_reflexo_paymentstatus_reflexo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documenttype',
            name='uniq_document_type_per_reflexo_name',
        ),
        migrations.RemoveConstraint(
            model_name='paymentstatus',
            name='uniq_payment_status_per_reflexo_name',
        ),
        migrations.RemoveConstraint(
            model_name='paymenttype',
            name='uniq_payment_type_per_reflexo_name',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='reflexo',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='reflexo',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='reflexo',
        ),
    ]
