# Generated by Django 5.2.5 on 2025-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0006_remove_documenttype_uniq_document_type_per_reflexo_name_and_more'),
        ('patients_diagnoses', '0004_alter_patient_options_patient_local_id_and_more'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['reflexo_id', 'local_id', '-created_at'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historiales'},
        ),
        migrations.AddField(
            model_name='history',
            name='local_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID local (por empresa)'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('reflexo', 'local_id'), name='uniq_history_local_id_per_reflexo'),
        ),
    ]
