# Generated by Django 5.2.5 on 2025-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0007_alter_history_options_history_local_id_and_more'),
        ('patients_diagnoses', '0004_alter_patient_options_patient_local_id_and_more'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('patient',), name='uniq_active_history_per_patient'),
        ),
    ]
