# Generated by Django 5.2.5 on 2025-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0008_history_uniq_active_history_per_patient'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predeterminedprice',
            options={'ordering': ['reflexo_id', 'local_id', 'name'], 'verbose_name': 'Precio Predeterminado', 'verbose_name_plural': 'Precios Predeterminados'},
        ),
        migrations.AddField(
            model_name='predeterminedprice',
            name='local_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID local (por empresa)'),
        ),
        migrations.AddConstraint(
            model_name='predeterminedprice',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('reflexo', 'local_id'), name='uniq_predetermined_price_local_id_per_reflexo'),
        ),
    ]
