# Generated by Cascade to add reflexo FK to users table
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reflexo", "0001_initial"),
        ("users_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reflexo",
            field=models.ForeignKey(
                to="reflexo.reflexo",
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name="+",
                verbose_name="Empresa/Tenant",
            ),
        ),
    ]
