# Generated by Django 5.2.5 on 2025-09-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0003_create_users_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverificationcode',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Código de verificación de usuario', 'verbose_name_plural': 'Códigos de verificación de usuarios'},
        ),
    ]
