# Generated by Django 5.2.5 on 2025-09-08 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflexo', '0001_initial'),
        ('users_profiles', '0004_alter_userverificationcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expira en'),
        ),
        migrations.AlterField(
            model_name='userverificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
    ]
