# Generated by Django 5.2.5 on 2025-09-08 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflexo', '0001_initial'),
        ('users_profiles', '0005_userverificationcode_reflexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Usado'),
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='verification_type',
            field=models.CharField(default='password_change', max_length=50, verbose_name='Tipo de verificación'),
        ),
    ]
