# Generated by Django 5.2.5 on 2025-09-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflexo', '0001_initial'),
        ('users_profiles', '0006_userverificationcode_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
        migrations.AddField(
            model_name='userverificationcode',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
