# Generated by Django 5.2.5 on 2025-09-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profiles', '0008_fix_userverificationcode_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationcode',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email objetivo'),
        ),
    ]
