# Generated by Django 5.2.5 on 2025-09-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0003_remove_country_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': ('view',), 'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
