# Generated by Django 5.2.5 on 2025-09-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflexo', '0001_initial'),
        ('ubi_geo', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddField(
            model_name='province',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddField(
            model_name='region',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_district_per_reflexo_name'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_province_per_reflexo_name'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('reflexo', 'name'), name='uniq_region_per_reflexo_name'),
        ),
    ]
