# Generated by Django 5.2.5 on 2025-09-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0005_district_reflexo_province_reflexo_region_reflexo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='district',
            name='uniq_district_per_reflexo_name',
        ),
        migrations.RemoveConstraint(
            model_name='province',
            name='uniq_province_per_reflexo_name',
        ),
        migrations.RemoveConstraint(
            model_name='region',
            name='uniq_region_per_reflexo_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='reflexo',
        ),
        migrations.RemoveField(
            model_name='province',
            name='reflexo',
        ),
        migrations.RemoveField(
            model_name='region',
            name='reflexo',
        ),
    ]
