# Generated by Django 5.2.5 on 2025-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0006_remove_district_uniq_district_per_reflexo_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['province__region__ubigeo_code', 'province__ubigeo_code', 'ubigeo_code', 'name'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['region__ubigeo_code', 'ubigeo_code', 'name'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['ubigeo_code', 'name'], 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AddField(
            model_name='district',
            name='ubigeo_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código ubigeo'),
        ),
        migrations.AddField(
            model_name='province',
            name='ubigeo_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código ubigeo'),
        ),
        migrations.AddField(
            model_name='region',
            name='ubigeo_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código ubigeo'),
        ),
    ]
