# Generated by Django 5.2.5 on 2025-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0007_alter_district_options_alter_province_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['sequence', 'region__ubigeo_code', 'ubigeo_code', 'name'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AddField(
            model_name='province',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='N°'),
        ),
    ]
