# Generated by Django 5.2.5 on 2025-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_geo', '0008_alter_province_options_province_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['sequence', 'province__region__ubigeo_code', 'province__ubigeo_code', 'ubigeo_code', 'name'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AddField(
            model_name='district',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='N°'),
        ),
    ]
