# Generated by Django 5.2.5 on 2025-09-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reflexo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Reflexo')),
            ],
            options={
                'verbose_name': 'Perfil de Clínica',
                'verbose_name_plural': 'Perfiles de Clínica',
                'db_table': 'clinica_user_profile',
            },
        ),
    ]
