# Generated by Django 5.2.5 on 2025-09-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0007_alter_history_options_history_local_id_and_more'),
        ('reflexo', '0001_initial'),
        ('therapists', '0001_initial'),
        ('ubi_geo', '0009_alter_district_options_district_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['reflexo_id', 'local_id', 'first_name', 'last_name_paternal'], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.AddField(
            model_name='therapist',
            name='local_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID local (por empresa)'),
        ),
        migrations.AddConstraint(
            model_name='therapist',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('reflexo', 'local_id'), name='uniq_therapist_local_id_per_reflexo'),
        ),
    ]
