# Generated by Django 5.2.5 on 2025-09-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'permissions': [('view_all_tenants', 'Can view data across all tenants (disable tenant filtering)')], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
