# Generated by Django 5.2.5 on 2025-09-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_diagnoses', '0001_initial'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo', verbose_name='Empresa/Tenant'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('reflexo', 'code'), name='uniq_diagnosis_per_reflexo_code'),
        ),
    ]
