# Generated by Django 5.2.5 on 2025-09-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_diagnoses', '0002_diagnosis_reflexo_alter_diagnosis_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('patient', 'diagnose', 'diagnosis_date')},
        ),
    ]
