# Generated by Django 5.2.5 on 2025-09-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories_configurations', '0006_remove_documenttype_uniq_document_type_per_reflexo_name_and_more'),
        ('patients_diagnoses', '0003_alter_medicalrecord_unique_together'),
        ('reflexo', '0001_initial'),
        ('ubi_geo', '0009_alter_district_options_district_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['reflexo_id', 'local_id', '-created_at'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='patient',
            name='local_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID local (por empresa)'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__isnull', False)), fields=('reflexo', 'local_id'), name='uniq_patient_local_id_per_reflexo'),
        ),
    ]
