# Generated by Django 5.2.5 on 2025-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_diagnoses', '0004_alter_patient_options_patient_local_id_and_more'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diagnosis',
            name='uniq_diagnosis_per_reflexo_code',
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_diagnosis_code'),
        ),
    ]
