# Generated by Django 5.2.5 on 2025-09-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_reports', '0001_initial'),
        ('reflexo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='reflexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reflexo.reflexo'),
        ),
    ]
